receivers:
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      process:
      processes:
      paging:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"  # OTLP gRPC endpoint
      http:
        endpoint: "0.0.0.0:4318"  # OTLP HTTP endpoint

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:9464"

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheus ]