{
 "title": "Kafka Dashboard",
 "description": "Kafka resource usage and consumer lag overview",
 "tags": [ "Kafka" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "kafka_job_name",
    "label": "kafka_job_name",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_controllerstate, job)"
    }
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_controllerstate{job=\"$kafka_job_name\"}, instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_cluster_partition_replicascount{job=\"$kafka_job_name\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Consumers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Events Consumed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_event_total[$__rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Records Consumed",
   "type": "gauge",
   "description": "Records processed by the consumers. These are \"records\" from Kafka ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_record_total[$__rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Events Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_event_total[$__rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Records Consumed",
   "type": "timeseries",
   "description": "Records processed by the consumers. These are \"records\" from Kafka ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_record_total[$__rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Producers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Kafka Record Send",
   "type": "timeseries",
   "description": "Kafka producer \"send\" count with Message runner thread send count",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(kafka_producer_send_total[$__rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Batch Byte Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(rate(kafka_producer_batch_size_sum{topic=\"test-bytes\"}[$__rate_interval]) / rate(kafka_producer_batch_size_count{topic=\"test-bytes\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "(\n  rate(kafka_producer_compression_size_sum{topic=\"test\"}[$__rate_interval])\n  /\n  rate(kafka_producer_compression_size_count{topic=\"test\"}[$__rate_interval])\n)\n/\n(\n  rate(kafka_producer_compression_rate_sum{topic=\"test\"}[$__rate_interval])\n  /\n  rate(kafka_producer_compression_rate_count{topic=\"test\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Batch Compressed Byte Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_compression_size_sum[$__rate_interval]) / rate(kafka_producer_compression_size_count[$__rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Compression Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(kafka_producer_compression_rate_sum[$__rate_interval]) / rate(kafka_producer_compression_rate_count[$__rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages per Batch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "rate(kafka_producer_messages_per_batch_sum[$__rate_interval]) / rate(kafka_producer_messages_per_batch_count[$__rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Batch Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_batch_success_total[$__rate_interval]) / (rate(kafka_producer_batch_success_total[$__rate_interval]) + rate(kafka_producer_batch_failure_total[$__rate_interval])) * 100",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Serialization Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_batch_time_milliseconds_sum[$__rate_interval]) / rate(kafka_producer_batch_time_milliseconds_count[$__rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message Runner Send Sleep Time",
   "type": "timeseries",
   "description": "Message runner iteration sleep time",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "rate(kafka_producer_message_runner_sleep_time_milliseconds_sum[$__rate_interval]) / rate(kafka_producer_message_runner_sleep_time_milliseconds_count[$__rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message Runner Send Fail",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "kafka_producer_message_runner_send_fail_total",
     "legendFormat": "{{topic}}-{{thread}}"
    }
   ]
  },
  {
   "title": "Message Runner Send",
   "type": "timeseries",
   "description": "Kafka producer \"send\" count with Message runner thread send count",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "targets": [
    {
     "expr": "rate(kafka_producer_message_runner_send_total[$__rate_interval])",
     "legendFormat": "{{topic}}-{{thread}}"
    }
   ]
  },
  { "title": "Kafka CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$kafka_job_name\"}[1m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"$kafka_job_name\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Kafka Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Bytes In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(instance)(increase(kafka_server_brokertopicmetrics_bytesin_total{job=\"$kafka_job_name\",topic!=\"\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(instance)(increase(kafka_server_brokertopicmetrics_bytesout_total{job=\"$kafka_job_name\",topic!=\"\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(instance)(increase(kafka_server_brokertopicmetrics_messagesin_total{job=\"$kafka_job_name\",topic!=\"\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka log size by topic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_log_log_size{job=\"$kafka_job_name\",})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka log size by broker (disk space utilization)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_log_log_size{job=\"$kafka_job_name\",})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kafka Broker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Partitions Leader Per Broker",
     "type": "table",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "kafka_cluster_partition_replicascount{job=~\"$kafka_job_name\",topic=~\"$topic\"}"
      }
     ]
    },
    {
     "title": "Brokers Online",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kafka_server_replicamanager_leadercount{job=~\"$kafka_job_name\"})"
      }
     ]
    },
    {
     "title": "Under Replicated Partitions",
     "type": "stat",
     "description": "Under Replicated Partitions",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{job=~\"$kafka_job_name\"})"
      }
     ]
    },
    {
     "title": "Bytes In / Out Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"$kafka_job_name\",instance=~\"$broker\",topic!=\"\"}[2m]))by(instance)",
       "legendFormat": "Bytes Out [{{instance}}]"
      },
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"$kafka_job_name\",instance=~\"$broker\",topic!=\"\"}[2m]))by(instance)",
       "legendFormat": "Bytes In [{{instance}}]"
      }
     ]
    },
    {
     "title": "Total of Topics",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount{job=~\"$kafka_job_name\"})"
      }
     ]
    },
    {
     "title": "Active Controllers",
     "type": "stat",
     "description": "Active Controllers",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{job=~\"$kafka_job_name\"})"
      }
     ]
    },
    {
     "title": "Online Partitions",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_partitioncount{job=~\"$kafka_job_name\"})"
      }
     ]
    },
    {
     "title": "Offline Partitions",
     "type": "stat",
     "description": "Offline Partitions",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{job=~\"$kafka_job_name\"})"
      }
     ]
    },
    {
     "title": "Bytes Out Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(topic)(increase(kafka_server_brokertopicmetrics_bytesout_total{job=\"$kafka_job_name\",topic=\"\"}[$__interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Bytes In Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(topic)(increase(kafka_server_brokertopicmetrics_bytesin_total{job=\"$kafka_job_name\",topic=\"\"}[$__interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Messages In Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without(topic)(increase(kafka_server_brokertopicmetrics_messagesin_total{job=\"$kafka_job_name\",topic=\"\"}[$__interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "ZooKeeper Request Latency Ms",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{job=\"$kafka_job_name\",instance=~\"$broker\"})by(instance)",
       "legendFormat": "Broker: {{instance}}"
      }
     ]
    },
    {
     "title": "ZooKeeper Expires Per Sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum (irate(kafka_server_sessionexpirelistener_zookeeperexpires_total{job=\"$kafka_job_name\",instance=~\"$broker\"}[1m]))by(instance)",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "ZooKeeper Disconnects Per Sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum (irate(kafka_server_sessionexpirelistener_zookeeperdisconnects_total{job=\"$kafka_job_name\",instance=~\"$broker\"}[1m]))by(instance)",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "ISR expands by instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod)(rate(kafka_server_replicamanager_isrexpands_total[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Underreplicated partitions by topic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod)(kafka_server_replicamanager_underreplicatedpartitions)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Consumer lag by group",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "kafka_consumergroup_lag_sum", "legendFormat": "{{consumergroup}}" }
     ]
    }
   ]
  }
 ]
}