global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka1:7071']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['kafka-otel-collector:9464']